dist: bionic
language: python
python:
  - "3.6.9"
install:
  - sudo apt-get update
  - pip install cython
  - pip install numpy
  - pip install h5py
  - pip install pysam
  - pip install mappy
  - pip install https://github.com/timothyjamesbecker/TesorSV/releases/download/0.0.1/hfm-0.0.1.tar.gz
script:
  - data_prep.py -h
