dist: bionic
language: python
python:
  - "3.6.9"
install:
  - sudo apt-get update
  - pip install cython
  - pip install numpy
  - pip install h5py
  - pip install pysam
  - pip install mappy
  - pip install matplotlib
  - pip install https://github.com/timothyjamesbecker/hfm/releases/download/0.1.8/hfm-0.1.8.tar.gz
  - pip install https://github.com/timothyjamesbecker/TensorSV/releases/download/0.0.1/tensorsv-0.0.1.tar.gz
script:
  - data_prep.py -h
